name: iosApp
options:
  bundleIdPrefix: com.assignment.pokemon
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    dependencies:
      - framework: ../shared/build/XCFrameworks/debug/shared.xcframework
        embed: true
      - sdk: libsqlite3.tbd
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.assignment.pokemon.ios
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "PokéDex"
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0

  iosAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: iosAppTests
    dependencies:
      - target: iosApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.assignment.pokemon.ios.tests
